/**
 * Use case: WALLETS
 * -------------------
 * "Before opening a link" (see original spec, Use cases section).
 *
 * A wallet intercepts any external link the user is about to open (a link
 * in a token's metadata, a "visit site" button on a connected dApp, a link
 * pasted into the built-in search bar) and passes it through the oracle
 * before letting it through.
 *
 * Example import in a real wallet:
 *   import { guardExternalLink } from "./linkGuard";
 */
import { createReadClient, createWriteClient } from "../shared/genlayerClient";
import { ensureAnalyzed, UrlReport } from "../shared/oracleClient";
import { CONTRACT_ADDRESS } from "../shared/config";

export type LinkGuardDecision =
  | { action: "open"; report: UrlReport }
  | { action: "warn"; report: UrlReport }
  | { action: "block"; report: UrlReport };

/**
 * Production note: this uses `createWriteClient()` with a service account
 * generated by the wallet itself (not the user's) to pay the cost of
 * `analyze()` the first time a URL is seen. In a real wallet, that
 * service account should:
 *   1. Be a fixed account loaded from a secret manager, not generated on
 *      the fly on every call.
 *   2. Live in a backend/relay, never embedded in the client bundle.
 * See examples/README.md, "Production considerations" section.
 */
export async function guardExternalLink(url: string): Promise<LinkGuardDecision> {
  const readClient = createReadClient();
  const writeClient = createWriteClient();

  const report = await ensureAnalyzed(readClient, writeClient, CONTRACT_ADDRESS, url);

  // Decide off `risk_tier`, not `trust_score`. `risk_tier` is the field
  // consensus actually gates on (leader and every validator had to land
  // in the exact same bucket); `trust_score` is an informational number
  // that can vary between equally-valid runs and must never be used for
  // an automated pass/fail/warn decision.
  if (report.risk_tier === "high_risk") {
    return { action: "block", report };
  }
  if (report.risk_tier === "caution") {
    return { action: "warn", report };
  }
  return { action: "open", report };
}

/**
 * Example integration inside a wallet's click handler. `openUrl` would be
 * the wallet's real function for opening the link (new tab, in-app
 * browser, etc.).
 */
export async function onExternalLinkClick(
  url: string,
  openUrl: (u: string) => void,
): Promise<LinkGuardDecision> {
  const decision = await guardExternalLink(url);

  switch (decision.action) {
    case "open":
      openUrl(url);
      break;

    case "warn": {
      const proceed = window.confirm(
        `This site is flagged "${decision.report.risk_tier}" ` +
          `(trust score ${decision.report.trust_score}/100, shown for reference only). ` +
          `Oracle's reason: "${decision.report.reason}". Open anyway?`,
      );
      if (proceed) openUrl(url);
      break;
    }

    case "block": {
      // `risk_tier === "high_risk"` doesn't always mean phishing or
      // malware -- a site can also land there purely from a low
      // trust_score (e.g. gambling content, or the LLM just judging it
      // generally suspicious) with both flags false. Don't assume
      // malware as a fallback; lead with the oracle's own free-text
      // reason instead.
      let cause = "flagged high-risk by the oracle";
      if (decision.report.phishing) cause = "phishing";
      else if (decision.report.malware) cause = "malware";

      window.alert(
        `Blocked for safety: ${url} was classified as ${cause}. ` +
          `Reason: "${decision.report.reason}"`,
      );
      break;
    }
  }

  return decision;
}
